title: "Randomizer"
description: "Thoughts, Projects, and More"
# logo: "/assets/images/88x88.png" # displays before title

url: https://johnstonskj.github.io
repository: johnstonskj/johnstonskj.github.io

theme: minima # jekyll-theme-slate
# https://github.com/jekyll/minima/tree/v2.5.0
title_separator: "|"
breadcrumbs: true  # disabled by default
search: true
share: true
show_downloads: false
highlighter: pygments

timezone: America/Los_Angeles
locale: "en-US"

header_pages:
  - index.md
  - work.md
  - fun.md
  - audio.md
  - diving.md
  
author: "Simon Johnston"
email: johnstonskj@gmail.com
avatar: "/assets/images/bio-photo.jpg"
github_username: johnstonskj
linkedin_username: simonkjohnston
facebook_username: simonkjohnston
instagram_username: johnston4250

social:
  type:  Person
  links:
    - "https://facebook.com/simonkjohnston"
    - "https://instagram.com/johnston4250"
    - "https://www.linkedin.com/in/simonkjohnston"
    - "https://scholar.google.com/citations?user=oXcWSwYAAAAJ&hl=en"
    
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      comments: false
  - scope:
      path: "assets/img"
    values:
      image: true
      
exclude:
- .gitignore
