title: "Randomizer"
description: "Thoughts, Projects, and More"
logo: "/assets/img/avatars/hell_drib.jpg"

url: https://simonkjohnston.life
repository: johnstonskj/johnstonskj.github.io

theme: minima # https://github.com/jekyll/minima/tree/v2.5.0
title_separator: "⟫"
breadcrumbs: true
search: true
share: true
show_downloads: false
highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  
timezone: America/Los_Angeles
locale: "en-US"

header_pages:
  - index.md
  - work.md
  - fun.md
  - audio.md
  - diving.md
  
author: "Simon Johnston"
email: johnstonskj@gmail.com
avatar: "/assets/img/avatars/hell_drib.jpg"
github_username: johnstonskj
linkedin_username: simonkjohnston
facebook_username: simonkjohnston
instagram_username: johnston4250
# discourse_username: johnston4250
# slack_username: johnstonskj@gmail.com
# slack_channels: racket

social:
  type:  Person
  links:
    - "https://facebook.com/simonkjohnston"
    - "https://instagram.com/johnston4250"
    - "https://www.linkedin.com/in/simonkjohnston"
    - "https://scholar.google.com/citations?user=oXcWSwYAAAAJ&hl=en"
# https://www.rustaceans.org/johnstonskj

plugins:
  - jekyll-avatar
  - jekyll-gist
  - jekyll-feed

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      comments: false
  - scope:
      path: "assets/img"
    values:
      image: true
      sitemap: false
      
exclude:
- .gitignore
- _drafts
- jekyllx

jekyll_compose:
  auto_open: true
  draft_default_front_matter:
    description:
    image:
    category:
    tags:
  post_default_front_matter:
    description:
    image:
    category:
    tags:
    published: false
    sitemap: false

feed:
  categories:
    - audio
    - code
    - diving
    - work
  excerpt_only: true

google_analytics: UA-119764-4