title: "Simon Johnston"
description: "Thoughts, Projects, and More"
url: https://johnstonskj.github.io
repository: https://github.com/johnstonskj/johnstonskj.github.io
show_downloads: false
timezone: America/Los_Angeles

name: "Simon Johnston"
email: johnstonskj@gmail.com
github_username: johnstonskj

theme: jekyll-theme-slate

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      author: "Simon Johnston"

exclude:
- .gitignore