title: "Simon Johnston"
description: "Thoughts, Projects and More"
show_downloads: false

theme: jekyll-theme-slate

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      author: "Simon Johnston"