title: "Randomizer"
description: "Thoughts, Projects, and More"
# logo: "/assets/images/88x88.png" # displays before title

url: https://johnstonskj.github.io
repository: johnstonskj/johnstonskj.github.io

theme: minima # jekyll-theme-slate
title_separator: "|"
breadcrumbs: true  # disabled by default
search: true
share: true
show_downloads: false
highlighter: pygments

timezone: America/Los_Angeles
locale: "en-US"

author: "Simon Johnston"
email: johnstonskj@gmail.com
github_username: johnstonskj
avatar   : "/assets/images/bio-photo.jpg"
bio      : "My awesome biography constrained to a sentence or two goes here."

social:
  type:  Person
  links:
    - "https://facebook.com/simonkjohnston"
    - "https://instagram.com/johnston4250"
    - "https://www.linkedin.com/in/simonkjohnston"
    - "https://scholar.google.com/citations?user=oXcWSwYAAAAJ&hl=en"
    
minima:
  social_links:
    github: johnstonskj
    facebook: simonkjohnston
    instagram: johnston4250
    linkedin: simonkjohnston
    
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      read_time: true
      comments: false
      
exclude:
- .gitignore