#!/usr/bin/env zsh

PAGES_DIR=.
POSTS_DIR=./_posts
DRAFTS_DIR=./_drafts
ASSET_DIR=./assets
IMG_DIR=$ASSET_DIR/img
AVATAR_DIR=$ASSET_DIR/img/avatar
POSTS_IMG_DIR=$ASSET_DIR/img/posts

MD_EXT=md

usage() {
	bold=$(tput bold)
	normal=$(tput sgr0)
    echo "${bold}NAME${normal}"
    echo "\t$0 - Jekyll wrapper script"
    echo "${bold}SYNOPSIS${normal}"
    echo "\t$0 [new|page|post|promote] ARGS"
    echo "${bold}DESCRIPTION${normal}"
    echo "\tnew SITENAME"
    echo "\t\t- create a new site and add useful stuff"
    echo "\tpage FILENAME [layout] [title]"
    echo "\t\t- create a new page with optional layout/title"
    echo "\tpost TITLE"
    echo "\t\t- create a new post with the required title"
    echo "\tpromote FILENAME"
    echo "\t\t- create a new page or post from a draft"
    echo "${bold}AUTHOR${normal}"
    echo "\tWritten by Simon Johnston"
    echo "${bold}SEE ALSO${normal}"
    echo "\tJekyll; simple blog-aware static sites <https://jekyllrb.com/>"
}

new_site() {
    if [[ ${#@} == 0 ]] ; then
		echo "Error: must supply a site name"
		usage
    else
		if $output=$(jekyll new $1) ; then
		    mkdir -p $DRAFTS_DIR
	    	mkdir -p $POSTS_DIR
		    mkdir -p $AVATAR_DIR
	    	mkdir -p $POSTS_IMG_DIR
		    cat <<EOF >> .gitignore
tmp/
\#*\#
*~
EOF
			git add .gitignore
		else
			echo "Error: could not create new site '$1' ($output)"
		fi
	fi
}

new_post() {
    if [[ ${#@} == 0 ]] ; then
	echo "Error: must supply file name"
	usage
    else
	DATE=$(date "+%Y-%m-%d")
	FILE=$(echo $1 | sed -e "s/ /-/g")
	echo "$POSTS_DIR/$DATE-$FILE.md"
 	cat <<EOF > "$POSTS_DIR/$DATE-$FILE.md"
---
title: $1
layout: post
---

TBD

EOF
	git add "$POSTS_DIR/$DATE-$FILE.md"
    fi
}

new_page() {
    if [[ ${#@} == 0 ]] ; then
	echo "Error: must supply file name"
	usage
    else
	FILE=$(basename -- $1)
	if [[ "${FILE##*.}" != $MD_EXT ]] ; then
	    FILE="$1.$MD_EXT"
	fi
	LAYOUT=${2:-default}
	TITLE=${3:-"New Page"}
	echo "Writing to $FILE"
 	cat <<EOF > "$PAGES_DIR/$FILE"
---
title: $TITLE
layout: $LAYOUT
---

TBD

EOF
    fi
    git add "$PAGES_DIR/$FILE"
}

promote() {
    if [[ ${#@} == 0 ]] ; then
		echo "Error: must supply file name"
		usage
    else
    	SRC="$DRAFTS_DIR/$1"
	    if [[ ! -e $SRC ]] ; then
			echo "Error: file $1 does not exist in $DRAFTS_DIR"
			usage
		else
			if grep -Fq "^layout: post" $SRC ; then
				DATE=$(date "+%Y-%m-%d")
				TITLE=$(grep "^title: " $SRC | cut -d: -f2 | sed -e "s/ /-/g")
			    git mv $SRC "$POSTS_DIR/$DATE-$TITLE.md"
			else
				git mv $SRC "$PAGES_DIR/$1"
			fi
		fi
	fi
}

case $1
in
    init)     new_site ;;
    
    new)      shift ;
	          new_file $@ ;;
	          
    post)     shift ;
	          new_post $@ ;;
	   
	promote)  shift ;
			  promote $@ ;;
    help)     usage ;;
    
    *)        usage ;;
esac
